version: '3'
services:
  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "${HOST_DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ${HOST_APP_FOLDER}/config/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
  sirene:
    build: ${HOST_APP_FOLDER}
    image: ${SIRENE_IMAGE_NAME}
    command: bin/rails server --port 3000 --binding 0.0.0.0
    depends_on:
      - db
    ports:
      - "${HOST_SOLR_PORT}:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - WAIT_HOSTS=db:5432
    volumes:
      - ${HOST_APP_FOLDER}/.last_monthly_stock_applied/:/docker_build/.last_monthly_stock_applied/
      - ${HOST_APP_FOLDER}/tmp/:/docker_build/tmp/
      - ${HOST_APP_FOLDER}/log/:/docker_build/log/
      - ${HOST_APP_FOLDER}/solr/default/data/:/docker_build/solr/default/data/
      - ${HOST_APP_FOLDER}/solr/development/data/:/docker_build/solr/development/data/
      - ${HOST_APP_FOLDER}/solr/sandbox/data/:/docker_build/solr/sandbox/data/
      - ${HOST_APP_FOLDER}/solr/production/data/:/docker_build/solr/production/data/
      - ${HOST_APP_FOLDER}/solr/test/data/:/docker_build/solr/test/data/
    links:
      - db
