---
development:
  solr:
    hostname: localhost
    port: 8982
    log_level: 'OFF'
    path: /solr/development
    memory: 1G

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: 'OFF'
    path: /solr/test
