sandbox:
  solr:
    hostname: localhost
    port: 8984
    log_level: OFF
    path: /solr/sandbox
    memory: 4G

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: OFF
    path: /solr/development
    memory: 4G # Use large memory usage (4G or more) when building the suggester dictionnary

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: OFF
    path: /solr/test

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF
    path: /solr/production
    memory: 8G
